WriteFile, PrintError update.
WriteFile: redundant 'if' condition.
PrintError: %X in format string requires 'unsigned int' but the argument type is 'DWORD {aka unsigned long}'.